'use strict';window.StackExchange={};function MSIsPlayback(){try{return parent&&parent.WebPlayer}catch(d){return!1}}if(!MSIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){function d(){$(document).on("click",".convert-to-post",function(a){a.preventDefault();a=$(this).attr("data-confirm");(!a||confirm(a))&&$("<form method='post'/>").attr("action",$(this).attr("href")).appendTo("body").append($("<input type='hidden' name='fkey' />").attr("value",$(this).attr("data-fkey"))).submit()})}function a(){function a(h){StackExchange.options.user.fkey!==h&&(StackExchange.options.user.fkey=h,$("input[name=fkey]").val(h))}function c(){var a=localStorage.getItem(d);
if(!a)return{time:0};a=a.split(/,/);return{fkey:a[0],time:parseInt(a[1],10)}}var d="se:fkey";$(window).on("storage",function(h){h=h.originalEvent;h.key==d&&h.newValue&&a(h.newValue.split(/,/)[0])});try{var h=StackExchange.options.user.fkey,e=c();if(e.fkey!==h)if(StackExchange.options.serverTime>e.time)try{localStorage.setItem(d,h+","+StackExchange.options.serverTime)}catch(f){}else a(e.fkey)}catch(p){}}var c=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){c(a)},
1E3);else{var d=document.createElement("div");d.id="noscript-padding";var e=document.createElement("div");e.id="noscript-warning";e.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(e)}},e=function(){var a=function(a){a?$(a).trigger("popupClose").fadeOutAndRemove():($("#lightbox:not(.no-esc-remove), .message-dismissable, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),
$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide(),$("#lightbox:not(.no-esc-remove), .message-dismissable, .popup, .share-tip, .esc-remove, .esc-hide").trigger("popupClose",{closeTrigger:"esc"}))};$(document).keyup(function(c){27==c.which&&a()});$("body").mousedown(function(a){var c=$(a.target);if(!c.closest(".ac_results, .popup").length){if(!c.closest(".popup").length){if(1!=a.which)return;$(".popup, #lightbox").fadeOutAndRemove().trigger("popupClose",
{closeTrigger:"click outside"})}c.closest(".share-tip").length||$(".share-tip").fadeOutAndRemove().trigger("popupClose",{closeTrigger:"click outside"});c.closest(".wmd-prompt-dialog").length||$(".wmd-prompt-dialog, .wmd-prompt-background").fadeOutAndRemove().trigger("popupClose",{closeTrigger:"click outside"})}});$(document).bind("closePopups",function(c){a(c.selectorToClose)})},f=function(){var a=$("#hlinks"),c=$("#search input[name=q]"),d=c.width(),h=2.5*d,e,f=function(a){c.queue("expand",a)},p=
!1,o=!("placeholder"in document.createElement("input"));o&&!StackExchange.options.isMobile&&(""==c[0].value&&(c[0].value="search"),c.bind({focus:function(){"search"==this.value&&(this.value="")}}));c.keydown(function(d){if(p||46>d.keyCode&&8!=d.keyCode&&32!=d.keyCode)return!0;p=!0;clearTimeout(e);c.clearQueue("expand");f(function(h){c[0].placeholder="";a.fadeOut(100,h)});f(function(a){c.animate({width:h,"max-width":h},100,a)});f(function(){0==c.parent().find(".search-prompt").length&&c.before('<span class="search-prompt">search:</span>')});
3==c.queue("expand").length&&c.dequeue("expand")}).focusout(function(){e=setTimeout(function(){f(function(a){c.parent().find(".search-prompt").remove();a()});f(function(a){c.animate({width:d,"max-width":d},100,a)});f(function(h){o&&""==c[0].value&&(c[0].value="search");c[0].placeholder="search";a.fadeIn(100,h)});3==c.queue("expand").length&&c.dequeue("expand");p=!1},200)});$("#search").keydown(function(a){if(13==a.which&&a.ctrlKey&&c.val())return window.open("/search?q="+encodeURIComponent(c.val()),
"_newtab"),!1}).find("input[name=q]").keyup(function(a){27==a.which&&$(this).blur()})};return function(g){StackExchange.options=g;g.serverTimeOffsetSec=g.serverTime-(new Date).getTime()/1E3;c(g.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();$(function(){e();f();a();d();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,g.fullPostfix);var c=StackExchange.options.styleCodeAdditionalLang;
c&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+c)});StackExchange.ready(function(){genuwine.init(g.user.accountId||null,g.user.inboxUnviewedCount,g.user.notificationsUnviewedCount);g.user.messages&&StackExchange.notify.showMessages(g.user.messages,g.isMobile);g.site.globalAuthDisabled||(!g.site.isChildMeta&&g.user.isAnonymous&&gauth.checkStackAuth(g.stackAuthUrl),gauth.informStackAuth(g.stackAuthUrl));g.user.isAnonymous||profileLink.init(g.user.gravatar,
g.isMobile,g.user.profileUrl+"?tab=activity",g.serverTimeOffsetSec);g.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(d){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(d).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(d){StackExchange.initialized.done(d)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var d={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",tagSuggestions:"tagsuggestions.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",mockups:"external-editor.js",schematics:"external-editor.js",
review:"review.js",translation:"full.js",gps:"full-anon.js",postValidation:"post-validation.js",exploreQuestions:"explore-qlist.js",eventCharts:"events.js"},a={},c={},e,f={},g=function(a,c){return function(h){var d=a[h];d||(d=a[h]=c(h));return d}},k=function(c){var c=a[c],h,d=$.Deferred(),e=$.when(d),f;if(c)for(h=0;h<c.length;h++)(f=c[h].call(null))&&$.isFunction(f.promise)&&(e=$.when(e,f));d.resolve();return e},j=function(){if(!e){var a=$("script[src*='/stub.js']:first");0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),
e="/content/js/"):e=a.attr("src").replace(/\/stub\.js.*$/,"/")}return e},h=function(a){var c=$.Deferred(),h=document.createElement("script");h.async="async";h.type="text/javascript";h.src=a;h.onload=h.onreadystatechange=function(a,d){if(!h.readyState||/loaded|complete/.test(h.readyState))d?c.reject():c.resolve()};h.onerror=function(){c.reject()};$("head")[0].appendChild(h);return c.promise()},l=function(a){a=d[a];return!a?$.Deferred().reject().promise():u(a)},u=g({},function(a){var c=j()+a;var d=
f["js/"+a];d?a="?v="+d:(StackExchange.debug.log("no cache breaker for "+a),a="");return h(c+a)}),p=g({},function(a){function c(){(d=StackExchange[a])?k(a).done(function(){h.resolve()}):0<e?(e--,StackExchange.debug.log("retrying "+a),setTimeout(c,20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),h.reject())}var h=$.Deferred(),d=StackExchange[a],e=3;d?h.resolve():l(a).done(c).fail(h.reject);return h.promise()}),o=$.Deferred(),t=function(a,c,h,e){if(!h&&!o.isResolved())o.done(function(){t(a,
c)});else{if(h)for(var f in d)d.hasOwnProperty(f)&&(d[f]=d[f].replace(/^(full(?:-anon)?).js$/,"$1"+(e||"")+".js"));e=p(a);h?o.resolve():e=$.when(e,StackExchange.initialized);e.done(function(){c()}).fail(function(){StackExchange.debug.log("failed to provide object "+a)});return e}};t.setCacheBreakers=function(a){for(var c in a)a.hasOwnProperty(c)&&(f[c]=a[c])};StackExchange.using=t;StackExchange.ifUsing=function(h,d,e){if("undefined"!==typeof e){if(c["u_"+e])return;c["u_"+e]=!0}StackExchange[h]?d():
((e=a[h])||(e=a[h]=[]),e.push(d))};StackExchange.loadJsFile=function(a){return h(j()+a)}})();String.prototype.formatUnicorn=function(){var d=this.toString();if(!arguments.length)return d;var a=typeof arguments[0],a="string"==a||"number"==a?arguments:arguments[0],c;for(c in a)d=d.replace(RegExp("\\{"+c+"\\}","gi"),a[c]);return d};String.prototype.truncate=function(d,a){var c=this.toString();d&&c.length>d&&(c=c.substr(0,d)+a);return c};
String.prototype.splitOnLast=function(d){d=this.lastIndexOf(d);return 0>d?[this]:[this.substr(0,d),this.substr(d)]};String.prototype.contains=function(d){return-1<this.indexOf(d)};
StackExchange.init.createJqueryExtensions=function(){var d=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,c,d){c=d[3];a=$(a).data(c);switch(typeof a){case "undefined":return!1;case "boolean":return a;case "object":return null!==a}return!0}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},track:function(){return this.each(function(){var a=$(this),c=a.is("a[href]")?a:a.find("a[href]"),
d=a.data("tracker");c.each(function(){var a=this.href.splitOnLast("#"),c=a[0];this.href=c+=(c.contains("?")?"&":"?")+d+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var c=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),e=this;$(this).bind("blur focus keyup paste charCounterUpdate",d.DelayedReaction(function(){var d=a.min,
g=a.max,k=a.setIsValid||function(){},j=e.value?e.value.replace(/\r\n/g,"\n").length:0,h=j>0.8*g?"supernova":j>0.6*g?"hot":j>0.4*g?"warm":"cool",l="";0==j?0==d?(l="enter up to "+g+" charcters",k(!0)):(l="enter at least "+d+" characters",k(!1)):j<d?(l=d-j+" more to go...",k(!1)):(d=g-j,l=0<=d?d+" character"+(1!=d?"s":"")+" left":"too long by "+Math.abs(d)+" character"+(-1!=d?"s":""),k(j<=g));c.text(l);c.hasClass(h)||c.removeClass("supernova hot warm cool").addClass(h)},100,{sliding:!0}).trigger)})},
selectRange:function(a,c){return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(a,c);else if(this.createTextRange){var d=this.createTextRange();d.collapse(!0);d.moveEnd("character",c);d.moveStart("character",a);d.select()}})},addSpinner:function(a){return this.each(function(){d.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(d.getSpinnerImg(a))})},addSpinnerBefore:function(a){return this.each(function(){$(this).before(d.getSpinnerImg(a))})},
removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorMessage:function(a,c){return this.each(function(){d.showErrorMessage(this,a,c)})},showErrorPopup:function(a,c){return this.each(function(){d.showErrorMessage(this,a,c)})},showInfoMessage:function(a,c){return this.each(function(){d.showInfoMessage(this,a,c)})},center:function(a){var a=a||{},c=this.parent();"static"===c.css("position")&&(c=c.offsetParent());var c=c.offset(),d=$(window),a=a.top||
Math.max((d.height()-this.outerHeight())/2+d.scrollTop()-c.top+(a.dy||0),0);this.css("position","absolute");this.css("top",a+"px");this.css("left",Math.max(20,(d.width()-this.outerWidth())/2+d.scrollLeft()-c.left)+"px");a="calc(50% - "+this.outerWidth()/2+"px)";this.css("left",a);this.css("left","-webkit-"+a);return this},helpOverlay:function(){d.bindHelpOverlayEvents(this);return this},hideHelpOverlay:function(){d.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?
this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):this.attr("disabled","disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var c=this;c.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(d){var f=$(d).elementNodesOnly();f.find(".popup-actions-cancel, .popup-close a").click(function(){StackExchange.helpers.closePopups(".popup");a.lightbox&&
$("#lightbox").fadeOutAndRemove()});f.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");a.hideDescriptions&&f.find("ul.action-list > li:not(.action-selected) .action-desc").hide();d=f.find("input:radio:not(.action-subform input)");d.closest("li").bind("hide-action",function(){var c=$(this),h=".action-subform"+(a.hideDescriptions?", .action-desc":"");c.removeClass("action-selected").find(h).slideUp("fast")}).bind("show-action",function(){var c=$(this);c.hasClass("action-selected")||
(c.siblings(".action-selected").trigger("hide-action"),c.addClass("action-selected").find(".action-subform").slideDown("fast",function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var c=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);c.length&&c.focus()}}),a.hideDescriptions&&c.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(c),f.find(".popup-submit").enable())});d.click(function(){$(this).closest("li").trigger("show-action")});
f.appendTo(c.parent());a.loaded&&a.loaded(f);d=function(){};if(a.subformShow){var g=f.find("li.action-selected .action-subform");0<g.length&&(d=function(){g.each(function(){a.subformShow($(this))})})}if(a.lightbox){var k=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");f.css("z-index",k.css("z-index")+1)}a.dontCenter||f.center().fadeIn("fast",d)},error:function(a){var d=a.responseText||"Unable to load popup - please try again";c.parent().showErrorMessage(d,
{"transient":409==a.status})},complete:d.removeSpinner});return c},asyncLoad:function(){return this.each(function(){var a=$(this),c=a.find(".async-load");a.hasClass(".async-load")&&(c=c.add(a));c.each(function(){var a=$(this),c=a.data("load-url")||"";c&&!a.is(":working")&&(a.working(!0).addSpinner(),$.ajax({type:"GET",url:c,dataType:"html"}).done(function(c){a.html(c).removeClass("async-load").mathjax();if(c=a.data("after-load")||""){for(var c=c.split("."),d,f=0;f<c.length;f++)d=(d||window)[c[f]];
"function"===typeof d&&d(a)}}).fail(function(){a.removeSpinner().showErrorMessage("An error has occurred; please try again")}))})})},mathjax:function(){return this.each(function(){"undefined"!=typeof MathJax&&MathJax.Hub.Typeset(this)})},elementNodesOnly:function(){return this.filter(function(){return 1===this.nodeType})}})};
StackExchange.helpers=function(){function d(a,c,d){for(var f=0;f<d.length;f++){var e=d[f];try{if(/\*/.test(e))for(var g=0;4>g;g++){var j=e.replace(/\*/g,k[g]),v=a.css(j);c.css(j,v)}else c.css(e,a.css(e))}catch(q){}}}function a(a,c,e,f){if(a.is(":visible")){var g=$.browser.msie?0:0.4;e()?(a.css("opacity",g+(f?0.2:0)),a.addClass("edit-field-overlayed"),e=a.prev(".actual-edit-overlay"),0==e.length&&(f=$.trim(a.parent().find("span.edit-field-overlay").text()),e=a.width(),g=a.height(),e=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:e,height:g}),e.is("textarea,input")?(e.val(f),d(c,e,["line-height"])):e.text(f).css("line-height",g+"px").prepend("&nbsp;"),d(c,e,["font-family","font-size","text-align"]),d(a,e,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),e.insertBefore(a),f=a.offset().top-
e.offset().top,0!=f&&(c=parseInt(e.css("margin-top")),f=c+f,a.is("textarea")||(f=parseInt(e.prevAll(":visible").eq(0).css("margin-bottom"))+c),e.css("margin-top",f)),a=a.offset().left-e.offset().left,0!=a&&(c=parseInt(e.css("margin-left")),e.css("margin-left",c+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function c(a,c){$(a).find("input[type='submit']").prop("disabled",c)}var e,f,g,k=["left","right","top","bottom"],j={bindMovablePopups:function(){var a=function(){e=
f=null;$("body").removeAttr("style")};$("div.popup").each(function(a,c){var d=$(c).find(".handle");d.length&&(d.css({cursor:"move"}),d.unbind("mousedown").bind("mousedown",function(a){var d=$(c).offset();f={x:d.left-a.pageX,y:d.top-a.pageY};e=$(c);d=e.offset();e.offset(d).offset(d);$("body").attr("style","cursor:move");a.preventDefault()}))});g||(g=!0,$(document).on("mousemove",function(a){e&&e.offset({top:a.pageY+f.y,left:a.pageX+f.x})}).on("keypress",a).on("mouseup",a))},genericBindOverlayEvents:function(c,
d,e){StackExchange.options.isMobile||d.bind("keydown contextmenu",function(){j.hideHelpOverlay(c)}).focus(function(){a(c,d,e,!0)}).on("blur change",function(){a(c,d,e)}).each(function(){a(c,d,e)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);j.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(a){if(null!=StackExchange.cardiologist){a.preventDefault();
var c=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=null;window.location.href=c});return!1}});return!0},showMessage:function(a,c,d){var e,f,g,j,a=$(a);if(a.length){d=$.extend({},{position:"inside",dismissable:!0,type:"error",closeOthers:!0},d);d.closeOthers&&$(".message").fadeOutAndRemove();var k=$('<div class="message"><div class="message-inner"><div class="message-text"></div></div></div>'),q=k.find(".message-inner"),n=k.find(".message-text");k.addClass("message-"+
d.type);n.html(c);d.dismissable&&(k.addClass("message-dismissable"),n.css("padding-right","35px"),q.prepend('<div class="message-close" title="close this message (or hit Esc)">&times;</div>'),k.click(function(a){$(a.target).is("a")||k.fadeOutAndRemove()}));d.css&&k.css(d.css);"inside"!=d.position&&"inline"!=d.position&&!d.tip&&(d.tip=d.position.my);d.tip&&q.addClass("message-tip message-tip-"+d.tip.replace(" ","-"));if("inline"==d.position)a.append(k);else if("inside"==d.position)k.css("position",
"absolute"),a.append(k);else{k.css("position","absolute");a.offsetParent().append(k);var q=a.position(),n=a.outerWidth(!0),a=a.outerHeight(!0),r=k.outerWidth(),s=k.outerHeight();switch(d.position.at){case "top left":g=0;j=0;break;case "top center":g=0;j=n/2;break;case "top right":g=0;j=n;break;case "right top":g=0;j=n;break;case "right center":g=a/2;j=n;break;case "right bottom":g=a;j=n;break;case "bottom right":g=a;j=n;break;case "bottom center":g=a;j=n/2;break;case "bottom left":g=a;j=0;break;case "left bottom":g=
a;j=0;break;case "left center":g=a/2;j=0;break;case "left top":g=0,j=0}switch(d.position.my){case "left top":e=0;f=-9;break;case "top left":e=-9;f=0;break;case "top right":e=-9;f=r;break;case "right top":e=0;f=r+9;break;case "right bottom":e=s;f=r+9;break;case "bottom right":e=s+9;f=r;break;case "bottom left":e=s+9;f=0;break;case "left bottom":e=s,f=-9}k.css({top:q.top+g-e,left:q.left+j-f})}k.fadeIn();d.transient&&setTimeout(function(){k.fadeOutAndRemove()},Math.max(2500,40*c.length));return k}},
showErrorMessage:function(a,c,d){d=$.extend({},{position:"inside",type:"error"},d);return this.showMessage(a,c,d)},showErrorPopup:function(a,c,d){return this.showErrorMessage(a,c,d)},showInfoMessage:function(a,c,d){d=$.extend({},{position:"inside","transient":!0,type:"info"},d);return this.showMessage(a,c,d)},removeMessages:function(){$(".message").fadeOutAndRemove()},addSpinner:function(a,c){$(a).append(j.getSpinnerImg(c))},getSpinnerImg:function(a){var c=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');
a&&c.css(a);return c},removeSpinner:function(){$("img.ajax-loader").remove()},closePopups:function(a){var c=$.Event("closePopups");c.selectorToClose=a;$(document).trigger(c)},enableSubmitButton:function(a){c(a,!1)},disableSubmitButton:function(a){c(a,!0)},loadTicks:function(a){var c;c=a?a.find(".edit-block"):$(".edit-block");0==c.find("input[name=i1l]").length&&!c.data("loading-ticks")&&(c.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){c.append("<input type='hidden' name='i1l' value='"+
a+"' />")},complete:function(){c.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},c=$("#overlay-header"),d=a.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(d+='<br><a class="close-overlay">close this message</a>');c.html(d).css(e).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){c.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(a,c,d){var d=d||{},e,f,g=d.always,j=function(){e=
null;a.apply(null,f)};return{trigger:function(){f=arguments;g&&g.apply(null,f);e?d.sliding&&(clearTimeout(e),e=setTimeout(j,c)):e=setTimeout(j,c)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return j}();
function prepareEditor(d){var a=d.postfix||"",c=function(){setTimeout(function(){StackExchange.editor.initIfShown(d)},1)};if(d.onDemand){for(var e="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),f=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),g=0,k=0;k<e.length;k++){var j=e[k],h=/spacer/.test(j),j=$("<li id='wmd-"+j+a+
"' />").prop("className","wmd-"+(h?"spacer":"button")).css("left",25*k).appendTo(f);$("<span />").css("background-position",g+"px -20px").appendTo(j);h||(g-=20)}var l=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){l||(l=!0,f.addSpinner({"float":"right"}),StackExchange.using("editor",function(){f.remove();d.autoShowMarkdownHelp&&(d.immediatelyShowMarkdownHelp=!0);c()}))})}else StackExchange.using("editor",c)}
StackExchange.switchMobile=function(d,a){$.post("/mobile/"+d,{returnurl:a},function(a){window.location=a})};StackExchange.switchLocale=function(d,a){$.post("/locale/"+d,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(d,a,c){if("undefined"!=typeof a){c=c||{};null===a&&(a="",c.expires=-1);var e="";if(c.expires&&("number"==typeof c.expires||c.expires.toUTCString))"number"==typeof c.expires?(e=new Date,e.setTime(e.getTime()+864E5*c.expires)):e=c.expires,e="; expires="+e.toUTCString();var f=c.path?"; path="+c.path:"",g=c.domain?"; domain="+c.domain:"",c=c.secure?"; secure":"";document.cookie=[d,"=",encodeURIComponent(a),e,f,g,c].join("")}else{a=null;if(document.cookie&&""!=document.cookie){c=
document.cookie.split(";");for(e=0;e<c.length;e++)if(f=jQuery.trim(c[e]),f.substring(0,d.length+1)==d+"="){a=decodeURIComponent(f.substring(d.length+1));break}}return a}};jQuery.expr[":"].regex=function(d,a,c){var a=c[3].split(","),e=/^(data|css):/,c=a[0].match(e)?a[0].split(":")[0]:"attr",e=a.shift().replace(e,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(d)[c](e))};
$.extend($.expr[":"],{containsExact:function(d,a,c){return $.trim(d.innerHTML.toLowerCase())===c[3].toLowerCase()},containsExactCase:function(d,a,c){return $.trim(d.innerHTML)===c[3]},containsRegex:function(d,a,c){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(c[3]);return RegExp(a[1],a[2]).test($.trim(d.innerHTML))}});
$.extend({URLEncode:function(d){for(var a="",c=0,d=d.toString(),e=/(^[a-zA-Z0-9_.]*)/;c<d.length;){var f=e.exec(d.substr(c));null!=f&&1<f.length&&""!=f[1]?(a+=f[1],c+=f[1].length):(" "==d[c]?a+="+":(f=d.charCodeAt(c).toString(16),a+="%"+(2>f.length?"0":"")+f.toUpperCase()),c++)}return a},URLDecode:function(d){for(var a,c=/(%[^%]{2})/;null!=(m=c.exec(d))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),d=d.replace(m[1],a);return d}});
(function(d){d.fn.typeWatch=function(a){function c(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var c={timer:null,text:d(a).val().toUpperCase(),cb:e.callback,el:a,wait:e.wait};e.highlight&&d(a).focus(function(){this.select()});var k=function(a){var f=c.wait,k=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(f=1,k=!0);clearTimeout(c.timer);c.timer=setTimeout(function(){var a=k,f=d(c.el).val();if(f.length>e.captureLength&&f.toUpperCase()!=c.text||a&&f.length>e.captureLength)c.text=
f.toUpperCase(),c.cb(f)},f)};d(a).keydown(k).bind("paste",null,function(a){a.which||k(this)}).bind("input",null,function(a){a.which||k(this)})}}var e=d.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){c(this)})}})(jQuery);
(function(d){function a(a){var f;return a&&a.constructor==Array&&3==a.length?a:(f=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(f[1]),parseInt(f[2]),parseInt(f[3])]:(f=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(f[1]),2.55*parseFloat(f[2]),2.55*parseFloat(f[3])]:(f=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(f[1],16),parseInt(f[2],16),parseInt(f[3],16)]:
(f=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(f[1]+f[1],16),parseInt(f[2]+f[2],16),parseInt(f[3]+f[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?c.transparent:c[d.trim(a).toLowerCase()]}d.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(c,f){d.fx.step[f]=function(c){if(!c.colorInit){var e;e=c.elem;var j=f,h;do{h=d.curCSS(e,j);if(""!=h&&"transparent"!=h||d.nodeName(e,"body"))break;j="backgroundColor"}while(e=e.parentNode);
e=a(h);c.start=e;c.end=a(c.end);c.colorInit=!0}c.elem.style[f]="rgb("+[Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2]),255),0)].join()+")"}});var c={transparent:[255,255,255]}})(jQuery);StackExchange.gps=function(){StackExchange._gps_track=[];return{track:function(d,a){a=a||{};StackExchange._gps_track.push({evt:d,properties:a,now:(new Date).getTime()})}}}();
