'use strict';var Markdown={};
(function(){function m(f){return f}function x(){return!1}function p(){}function u(){}p.prototype={chain:function(f,o){var t=this[f];if(!t)throw Error("unknown hook "+f);this[f]=t===m?o:function(f){var n=Array.prototype.slice.call(arguments,0);n[0]=t.apply(null,n);return o.apply(null,n)}},set:function(f,o){if(!this[f])throw Error("unknown hook "+f);this[f]=o},addNoop:function(f){this[f]=m},addFalse:function(f){this[f]=x}};Markdown.HookCollection=p;u.prototype={set:function(f,o){this["s_"+f]=o},get:function(f){return this["s_"+
f]}};Markdown.Converter=function(){function f(a){return a=a.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?(?=\s|$)[ \t]*\n?[ \t]*((\n*)["(](.+?)[")][ \t]*)?(?:\n+)/gm,function(a,e,L,b,d,l){e=e.toLowerCase();F.set(e,c(L));if(d)return b;l&&G.set(e,l.replace(/"/g,"&quot;"));return""})}function o(a){a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,m);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math)\b[^\r]*?.*<\/\2>[ \t]*(?=\n+)\n)/gm,
m);a=a.replace(/\n[ ]{0,3}((<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,m);a=a.replace(/\n\n[ ]{0,3}(<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>[ \t]*(?=\n{2,}))/g,m);return a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,m)}function m(a,c){var e;e=c.replace(/^\n+/,"");e=e.replace(/\n+$/g,"");return e="\n\n~K"+(H.push(e)-1)+"K\n\n"}function s(a,c){a=y.preBlockGamut(a,K);a=z(a);a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?-[ ]?){3,}[ \t]*$/gm,
"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?_[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=i(a);a=E(a);a=d(a);a=y.postBlockGamut(a,K);a=o(a);return a=b(a,c)}function n(a){a=y.preSpanGamut(a);a=v(a);a=x(a);a=a.replace(/\\(\\)/g,B);a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,B);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,q);a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,q);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,A);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?((?:\([^)]*\)|[^()\s])*?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
A);a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,A);a=g(a);a=a.replace(/~P/g,"://");a=c(a);a=a.replace(/([\W_]|^)(\*\*|__)(?=\S)([^\r]*?\S[\*_]*)\2([\W_]|$)/g,"$1<strong>$3</strong>$4");a=a.replace(/([\W_]|^)(\*|_)(?=\S)([^\r\*_]*?\S)\2([\W_]|$)/g,"$1<em>$3</em>$4");a=a.replace(/  +\n/g," <br>\n");return a=y.postSpanGamut(a)}function x(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>)/gi,function(a){var c=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return c=
r(c,"!"==a.charAt(1)?"\\`*_/":"\\`*_")})}function A(a,c,e,b,d,k,g,B){void 0==B&&(B="");a=e.replace(/:\/\//g,"~P");b=b.toLowerCase();if(""==d)if(""==b&&(b=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=F.get(b))d=F.get(b),void 0!=G.get(b)&&(B=G.get(b));else if(-1<c.search(/\(\s*\)$/m))d="";else return c;d=l(d);d=r(d,"*_");c='<a href="'+d+'"';""!=B&&(B=j(B),B=r(B,"*_"),c+=' title="'+B+'"');return c+(">"+a+"</a>")}function j(a){return a.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}
function q(a,c,e,b,d,l,k,g){a=e;b=b.toLowerCase();g||(g="");if(""==d)if(""==b&&(b=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=F.get(b))d=F.get(b),void 0!=G.get(b)&&(g=G.get(b));else return c;a=r(j(a),"*_[]()");d=r(d,"*_");c='<img src="'+d+'" alt="'+a+'"';g=j(g);g=r(g,"*_");return c+(' title="'+g+'"')+" />"}function z(a){a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(a,c){return"<h1>"+n(c)+"</h1>\n\n"});a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,c){return"<h2>"+n(c)+"</h2>\n\n"});return a=
a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(a,c,e){a=c.length;return"<h"+a+">"+n(e)+"</h"+a+">\n\n"})}function i(a,c){var a=a+"~0",e=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;J?a=a.replace(e,function(a,e,b){a=-1<b.search(/[*+-]/g)?"ul":"ol";e=w(e,a,c);e=e.replace(/\s+$/,"");return"<"+a+">"+e+"</"+a+">\n"}):(e=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,a=a.replace(e,function(a,
c,e,b){a=-1<b.search(/[*+-]/g)?"ul":"ol";e=w(e,a);return c+"<"+a+">\n"+e+"</"+a+">\n"}));return a=a.replace(/~0/,"")}function w(a,c,e){J++;var a=a.replace(/\n{2,}$/,"\n"),c=M[c],b=!1,a=(a+"~0").replace(RegExp("(^[ \\t]*)("+c+")[ \\t]+([^\\r]+?(\\n+))(?=(~0|\\1("+c+")[ \\t]+))","gm"),function(a,c,d,l){a=l;(c=/\n\n$/.test(a))||-1<a.search(/\n{2,}/)||b?a=s(I(a),!0):(a=i(I(a),!0),a=a.replace(/\n$/,""),e||(a=n(a)));b=c;return"<li>"+a+"</li>\n"}),a=a.replace(/~0/g,"");J--;return a}function E(c){c=(c+"~0").replace(/(?:\n\n|^\n?)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(c,e,b){c=a(I(e));c=D(c);c=c.replace(/^\n+/g,"");c=c.replace(/\n+$/g,"");return"\n\n"+("<pre><code>"+c+"\n</code></pre>")+"\n\n"+b});return c=c.replace(/~0/,"")}function h(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(H.push(a)-1)+"K\n\n"}function v(c){return c=c.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(c,e,b,d){c=d.replace(/^([ \t]*)/g,"");c=c.replace(/[ \t]*$/g,"");c=a(c);c=c.replace(/:\/\//g,"~P");return e+"<code>"+c+"</code>"})}function a(a){a=a.replace(/&/g,"&amp;");
a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=r(a,"*_{}[]\\",!1)}function d(a){return a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,c){var e;e=c.replace(/^[ \t]*>[ \t]?/gm,"~0");e=e.replace(/~0/g,"");e=e.replace(/^[ \t]+$/gm,"");e=s(e);e=e.replace(/(^|\n)/g,"$1  ");e=e.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,c){var e;e=c.replace(/^  /mg,"~0");return e=e.replace(/~0/g,"")});return h("<blockquote>\n"+e+"\n</blockquote>")})}function b(a,c){for(var a=a.replace(/^\n+/g,
""),a=a.replace(/\n+$/g,""),e=a.split(/\n{2,}/g),b=[],d=/~K(\d+)K/,l=e.length,g=0;g<l;g++){var r=e[g];d.test(r)?b.push(r):/\S/.test(r)&&(r=n(r),r=r.replace(/^([ \t]*)/g,"<p>"),r+="</p>",b.push(r))}if(!c){l=b.length;for(g=0;g<l;g++)for(var k=!0;k;)k=!1,b[g]=b[g].replace(/~K(\d+)K/g,function(a,c){k=!0;return H[c]})}return b.join("\n\n")}function c(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?!]|~D)/gi,"&lt;")}function e(a,c,e,b){if(c)return a;if(")"!==
b.charAt(b.length-1))return"<"+e+b+">";for(var a=b.match(/[()]/g),d=c=0;d<a.length;d++)"("===a[d]?0>=c?c=1:c++:c--;var l="";0>c&&(b=b.replace(RegExp("\\){1,"+-c+"}$"),function(a){l=a;return""}));l&&(a=b.charAt(b.length-1),N.test(a)||(l=a+l,b=b.substr(0,b.length-1)));return"<"+e+b+">"+l}function g(a){a=a.replace(O,e);return a=a.replace(/<((https?|ftp):[^'">\s]+)>/gi,function(a,c){return'<a href="'+c+'">'+y.plainLinkText(c)+"</a>"})}function k(a){return a=a.replace(/~E(\d+)E/g,function(a,c){var e=parseInt(c);
return String.fromCharCode(e)})}function I(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")}function D(a){if(!/\t/.test(a))return a;var c=["    ","   ","  "," "],e=0,b;return a.replace(/[\n\t]/g,function(a,d){if("\n"===a)return e=d+1,a;b=(d-e)%4;e=d+1;return c[b]})}function l(a){if(!a)return"";var c=a.length;return a.replace(P,function(e,b){return"~D"==e?"%24":":"==e&&(b==c-1||/[0-9\/]/.test(a.charAt(b+1)))?":":"%"+e.charCodeAt(0).toString(16)})}function r(a,c,e){c="(["+c.replace(/([\[\]\\])/g,
"\\$1")+"])";e&&(c="\\\\"+c);return a=a.replace(RegExp(c,"g"),B)}function B(a,c){return"~E"+c.charCodeAt(0)+"E"}var y=this.hooks=new p;y.addNoop("plainLinkText");y.addNoop("preConversion");y.addNoop("postNormalization");y.addNoop("preBlockGamut");y.addNoop("postBlockGamut");y.addNoop("preSpanGamut");y.addNoop("postSpanGamut");y.addNoop("postConversion");var F,G,H,J;this.makeHtml=function(a){if(F)throw Error("Recursive call to converter.makeHtml");F=new u;G=new u;H=[];J=0;a=y.preConversion(a);a=a.replace(/~/g,
"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a=D("\n\n"+a+"\n\n");a=a.replace(/^[ \t]+$/mg,"");a=y.postNormalization(a);a=o(a);a=f(a);a=s(a);a=k(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");a=y.postConversion(a);H=G=F=null;return a};var K=function(a){return s(a)},M={ol:"\\d+[.]",ul:"[*+-]"},O=/(="|<)?\b(https?|ftp)(:\/\/[-A-Z0-9+&@#/%?=~_|[\]()!:,.;]*[-A-Z0-9+&@#/%=~_|[\])])(?=$|\W)/gi,N=/[-A-Z0-9+&@#/%=~_|[\])]/i,P=/(?:["'*()[\]:]|~D)/g}})();
(function(){var m,x,p;function u(){}function f(a){this.buttonBar=i.getElementById("wmd-button-bar"+a);this.preview=i.getElementById("wmd-preview"+a);this.input=i.getElementById("wmd-input"+a)}function o(a,d){var b=this,c=[],e=0,g="none",k,h,D,l=function(a,c){g!=a&&(g=a,c||B());!m||"moving"!=g?h=setTimeout(r,1):D=null},r=function(a){D=new t(d,a);h=void 0};this.setCommandMode=function(){g="command";B();h=setTimeout(r,0)};this.canUndo=function(){return 1<e};this.canRedo=function(){return c[e+1]?!0:!1};
this.undo=function(){b.canUndo()&&(k?(k.restore(),k=null):(c[e]=new t(d),c[--e].restore(),a&&a()));g="none";d.input.focus();r()};this.redo=function(){b.canRedo()&&(c[++e].restore(),a&&a());g="none";d.input.focus();r()};var B=function(){var b=D||new t(d);if(!b)return!1;"moving"==g?k||(k=b):(k&&(c[e-1].text!=k.text&&(c[e++]=k),k=null),c[e++]=b,c[e+1]=null,a&&a())},y=function(a){var c=!1;if((a.ctrlKey||a.metaKey)&&!a.altKey)switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "y":b.redo();
c=!0;break;case "z":a.shiftKey?b.redo():b.undo(),c=!0}c&&(a.preventDefault&&a.preventDefault(),window.event&&(window.event.returnValue=!1))},i=function(a){!a.ctrlKey&&!a.metaKey&&(a=a.keyCode,33<=a&&40>=a||63232<=a&&63235>=a?l("moving"):8==a||46==a||127==a?l("deleting"):13==a?l("newlines"):27==a?l("escape"):(16>a||20<a)&&91!=a&&l("typing"))};(function(){j.addEvent(d.input,"keypress",function(a){(a.ctrlKey||a.metaKey)&&!a.altKey&&(89==a.keyCode||90==a.keyCode)&&a.preventDefault()});var a=function(){if((m||
D&&D.text!=d.input.value)&&void 0==h)g="paste",B(),r()};j.addEvent(d.input,"keydown",y);j.addEvent(d.input,"keydown",i);j.addEvent(d.input,"mousedown",function(){l("moving")});d.input.onpaste=a;d.input.ondrop=a})();r(!0);B()}function t(a,d){var b=this,c=a.input;this.init=function(){if(j.isVisible(c)&&(d||!(i.activeElement&&i.activeElement!==c)))if(this.setInputAreaSelectionStartEnd(),this.scrollTop=c.scrollTop,!this.text&&c.selectionStart||0===c.selectionStart)this.text=c.value};this.setInputAreaSelection=
function(){if(j.isVisible(c))if(void 0!==c.selectionStart&&!x)c.focus(),c.selectionStart=b.start,c.selectionEnd=b.end,c.scrollTop=b.scrollTop;else if(i.selection&&!(i.activeElement&&i.activeElement!==c)){c.focus();var a=c.createTextRange();a.moveStart("character",-c.value.length);a.moveEnd("character",-c.value.length);a.moveEnd("character",b.end);a.moveStart("character",b.start);a.select()}};this.setInputAreaSelectionStartEnd=function(){if(!a.ieCachedRange&&(c.selectionStart||0===c.selectionStart))b.start=
c.selectionStart,b.end=c.selectionEnd;else if(i.selection){b.text=j.fixEolChars(c.value);var e=a.ieCachedRange||i.selection.createRange(),d=j.fixEolChars(e.text),k="\u0007"+d+"\u0007";e.text=k;var h=j.fixEolChars(c.value);e.moveStart("character",-k.length);e.text=d;b.start=h.indexOf("\u0007");b.end=h.lastIndexOf("\u0007")-1;if(k=b.text.length-j.fixEolChars(c.value).length){for(e.moveStart("character",-d.length);k--;)d+="\n",b.end+=1;e.text=d}a.ieCachedRange&&(b.scrollTop=a.ieCachedScrollTop);a.ieCachedRange=
null;this.setInputAreaSelection()}};this.restore=function(){void 0!=b.text&&b.text!=c.value&&(c.value=b.text);this.setInputAreaSelection();c.scrollTop=b.scrollTop};this.getChunks=function(){var a=new u;a.before=j.fixEolChars(b.text.substring(0,b.start));a.startTag="";a.selection=j.fixEolChars(b.text.substring(b.start,b.end));a.endTag="";a.after=j.fixEolChars(b.text.substring(b.end));a.scrollTop=b.scrollTop;return a};this.setChunks=function(a){a.before+=a.startTag;a.after=a.endTag+a.after;this.start=
a.before.length;this.end=a.before.length+a.selection.length;this.text=a.before+a.selection+a.after;this.scrollTop=a.scrollTop};this.init()}function s(a,d,b){var c,e,g,k=function(){var a=0;window.innerHeight?a=window.pageYOffset:i.documentElement&&i.documentElement.scrollTop?a=i.documentElement.scrollTop:i.body&&(a=i.body.scrollTop);return a},h=function(){if(d.preview){var c=d.input.value;if(!(c&&c==g)){g=c;var b=(new Date).getTime(),c=a.makeHtml(c);e=(new Date).getTime()-b;G(c)}}},D=function(){c&&
(clearTimeout(c),c=void 0);var a=0,a=e;3E3<a&&(a=3E3);c=setTimeout(h,a)};this.refresh=function(a){a?(g="",h()):D()};this.processingTime=function(){return e};var l=!0,r=function(a){var c=d.preview,e=c.parentNode,b=c.nextSibling;e.removeChild(c);c.innerHTML=a;b?e.insertBefore(c,b):e.appendChild(c)},B=function(a){d.preview.innerHTML=a},y,F=function(a){if(y)return y(a);try{B(a),y=B}catch(c){y=r,y(a)}},G=function(a){var c=q.getTop(d.input)-k();d.preview&&(F(a),b());d.preview&&(d.preview.scrollTop=(d.preview.scrollHeight-
d.preview.clientHeight)*(d.preview.scrollHeight<=d.preview.clientHeight?1:d.preview.scrollTop/(d.preview.scrollHeight-d.preview.clientHeight)));if(l)l=!1;else{var e=q.getTop(d.input)-k();m?setTimeout(function(){window.scrollBy(0,e-c)},0):window.scrollBy(0,e-c)}};(function(a,c){j.addEvent(a,"input",c);a.onpaste=c;a.ondrop=c;j.addEvent(a,"keypress",c);j.addEvent(a,"keydown",c)})(d.input,D);h();d.preview&&(d.preview.scrollTop=0)}function n(a,d,b,c,e,g,k){var h,D,l,r,B,y,F,G,v,q,o,n;function f(a){z.focus();
if(a.textOp){b&&b.setCommandMode();var e=new t(d);if(!e)return;var l=e.getChunks(),r=function(){z.focus();l&&e.setChunks(l);e.restore();c.refresh()};a.textOp(l,r)||r()}a.execute&&a.execute(b)}function s(a,c){var e=a.getElementsByTagName("span")[0];c?(e.style.backgroundPosition=a.XShift+" 0px",a.onmouseover=function(){e.style.backgroundPosition=this.XShift+" -40px"},a.onmouseout=function(){e.style.backgroundPosition=this.XShift+" 0px"},m&&(a.onmousedown=function(){i.activeElement&&i.activeElement!==
d.input||(d.ieCachedRange=document.selection.createRange(),d.ieCachedScrollTop=d.input.scrollTop)}),a.isHelp||(a.onclick=function(){if(this.onmouseout)this.onmouseout();f(this);return!1})):(e.style.backgroundPosition=a.XShift+" -20px",a.onmouseover=a.onmouseout=a.onclick=function(){})}function p(a){"string"===typeof a&&(a=e[a]);return function(){a.apply(e,arguments)}}function u(){b&&(s(o,b.canUndo()),s(n,b.canRedo()))}var z=d.input;h=void 0;D=void 0;l=void 0;r=void 0;B=void 0;y=void 0;F=void 0;G=
void 0;v=void 0;q=void 0;o=void 0;n=void 0;(function(){var c=d.buttonBar,e=document.createElement("ul");e.id="wmd-button-row"+a;e.className="wmd-button-row";var e=c.appendChild(e),b=0,c=function(c,d,l,r){var g=document.createElement("li");g.className="wmd-button";g.style.left=b+"px";b+=25;var k=document.createElement("span");g.id=c+a;g.appendChild(k);g.title=d;g.XShift=l;r&&(g.textOp=r);s(g,!0);e.appendChild(g);return g},i=function(c){var d=document.createElement("li");d.className="wmd-spacer wmd-spacer"+
c;d.id="wmd-spacer"+c+a;e.appendChild(d);b+=25};h=c("wmd-bold-button",k("bold"),"0px",p("doBold"));D=c("wmd-italic-button",k("italic"),"-20px",p("doItalic"));i(1);l=c("wmd-link-button",k("link"),"-40px",p(function(a,c){return this.doLinkOrImage(a,c,!1)}));r=c("wmd-quote-button",k("quote"),"-60px",p("doBlockquote"));B=c("wmd-code-button",k("code"),"-80px",p("doCode"));y=c("wmd-image-button",k("image"),"-100px",p(function(a,c){return this.doLinkOrImage(a,c,!0)}));i(2);F=c("wmd-olist-button",k("olist"),
"-120px",p(function(a,c){this.doList(a,c,!0)}));G=c("wmd-ulist-button",k("ulist"),"-140px",p(function(a,c){this.doList(a,c,!1)}));v=c("wmd-heading-button",k("heading"),"-160px",p("doHeading"));q=c("wmd-hr-button",k("hr"),"-180px",p("doHorizontalRule"));i(3);o=c("wmd-undo-button",k("undo"),"-200px",null);o.execute=function(a){a&&a.undo()};i=/win/.test(E.platform.toLowerCase())?k("redo"):k("redomac");n=c("wmd-redo-button",i,"-220px",null);n.execute=function(a){a&&a.redo()};g&&(c=document.createElement("li"),
i=document.createElement("span"),c.appendChild(i),c.className="wmd-button wmd-help-button",c.id="wmd-help-button"+a,c.XShift="-240px",c.isHelp=!0,c.style.right="0px",c.title=k("help"),c.onclick=g.handler,s(c,!0),e.appendChild(c));u()})();var A="keydown";x&&(A="keypress");j.addEvent(z,A,function(a){if((a.ctrlKey||a.metaKey)&&!a.altKey&&!a.shiftKey){switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "b":f(h);break;case "i":f(D);break;case "l":f(l);break;case "q":f(r);break;case "k":f(B);
break;case "g":f(y);break;case "o":f(F);break;case "u":f(G);break;case "h":f(v);break;case "r":f(q);break;case "y":f(n);break;case "z":a.shiftKey?f(n):f(o);break;default:return}a.preventDefault&&a.preventDefault();window.event&&(window.event.returnValue=!1)}});j.addEvent(z,"keyup",function(a){if(a.shiftKey&&!a.ctrlKey&&!a.metaKey&&13===(a.charCode||a.keyCode))a={},a.textOp=p("doAutoindent"),f(a)});m&&j.addEvent(z,"keydown",function(a){if(27===a.keyCode)return!1});this.setUndoRedoButtonStates=u}function C(a,
d){this.hooks=a;this.getString=d}function A(a){return a.replace(/^\s*(.*?)(?:\s+"(.+)")?\s*$/,function(a,b,c){b=b.replace(/\?.*$/,function(a){return a.replace(/\+/g," ")});b=decodeURIComponent(b);b=encodeURI(b).replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29");b=b.replace(/\?.*$/,function(a){return a.replace(/\+/g,"%2b")});c&&(c=c.trim?c.trim():c.replace(/^\s*/,"").replace(/\s*$/,""),c=c.replace(/"/g,"quot;").replace(/\(/g,"&#40;").replace(/\)/g,"&#41;").replace(/</g,"&lt;").replace(/>/g,
"&gt;"));return c?b+' "'+c+'"':b})}var j={},q={},z={},i=window.document,w=window.RegExp,E=window.navigator;m=/msie/.test(E.userAgent.toLowerCase());p=/msie 6/.test(E.userAgent.toLowerCase())||/msie 5/.test(E.userAgent.toLowerCase());x=/opera/.test(E.userAgent.toLowerCase());var h={bold:"Strong <strong> Ctrl+B",boldexample:"strong text",italic:"Emphasis <em> Ctrl+I",italicexample:"emphasized text",link:"Hyperlink <a> Ctrl+L",linkdescription:"enter link description here",linkdialog:'<p><b>Insert Hyperlink</b></p><p>http://example.com/ "optional title"</p>',
quote:"Blockquote <blockquote> Ctrl+Q",quoteexample:"Blockquote",code:"Code Sample <pre><code> Ctrl+K",codeexample:"enter code here",image:"Image <img> Ctrl+G",imagedescription:"enter image description here",imagedialog:"<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",olist:"Numbered List <ol> Ctrl+O",ulist:"Bulleted List <ul> Ctrl+U",litem:"List item",
heading:"Heading <h1>/<h2> Ctrl+H",headingexample:"Heading",hr:"Horizontal Rule <hr> Ctrl+R",undo:"Undo - Ctrl+Z",redo:"Redo - Ctrl+Y",redomac:"Redo - Ctrl+Shift+Z",help:"Markdown Editing Help"};Markdown.Editor=function(a,d,b){b=b||{};"function"===typeof b.handler&&(b={helpButton:b});b.strings=b.strings||{};b.helpButton&&(b.strings.help=b.strings.help||b.helpButton.title);var c=function(a){return b.strings[a]||h[a]},d=d||"",e=this.hooks=new Markdown.HookCollection;e.addNoop("onPreviewRefresh");e.addNoop("postBlockquoteCreation");
e.addFalse("insertImageDialog");this.getConverter=function(){return a};var g=this,k;this.run=function(){if(!k){k=new f(d);var h=new C(e,c),D=new s(a,k,function(){e.onPreviewRefresh()}),l,r;/\?noundo/.test(i.location.href)||(l=new o(function(){D.refresh();r&&r.setUndoRedoButtonStates()},k),this.textOperation=function(a){l.setCommandMode();a();g.refreshPreview()});r=new n(d,k,l,D,h,b.helpButton,c);r.setUndoRedoButtonStates();(g.refreshPreview=function(){D.refresh(!0)})()}}};u.prototype.findTags=function(a,
d){var b=this,c;a&&(c=j.extendRegExp(a,"","$"),this.before=this.before.replace(c,function(a){b.startTag+=a;return""}),c=j.extendRegExp(a,"^",""),this.selection=this.selection.replace(c,function(a){b.startTag+=a;return""}));d&&(c=j.extendRegExp(d,"","$"),this.selection=this.selection.replace(c,function(a){b.endTag=a+b.endTag;return""}),c=j.extendRegExp(d,"^",""),this.after=this.after.replace(c,function(a){b.endTag=a+b.endTag;return""}))};u.prototype.trimWhitespace=function(a){var d,b=this;a?a=d="":
(a=function(a){b.before+=a;return""},d=function(a){b.after=a+b.after;return""});this.selection=this.selection.replace(/^(\s*)/,a).replace(/(\s*)$/,d)};u.prototype.skipLines=function(a,d,b){void 0===a&&(a=1);void 0===d&&(d=1);a++;d++;var c,e;navigator.userAgent.match(/Chrome/)&&"X".match(/()./);this.selection=this.selection.replace(/(^\n*)/,"");this.startTag+=w.$1;this.selection=this.selection.replace(/(\n*$)/,"");this.endTag+=w.$1;this.startTag=this.startTag.replace(/(^\n*)/,"");this.before+=w.$1;
this.endTag=this.endTag.replace(/(\n*$)/,"");this.after+=w.$1;if(this.before){for(c=e="";a--;)c+="\\n?",e+="\n";b&&(c="\\n*");this.before=this.before.replace(new w(c+"$",""),e)}if(this.after){for(c=e="";d--;)c+="\\n?",e+="\n";b&&(c="\\n*");this.after=this.after.replace(new w(c,""),e)}};j.isVisible=function(a){if(window.getComputedStyle)return"none"!==window.getComputedStyle(a,null).getPropertyValue("display");if(a.currentStyle)return"none"!==a.currentStyle.display};j.addEvent=function(a,d,b){a.attachEvent?
a.attachEvent("on"+d,b):a.addEventListener(d,b,!1)};j.removeEvent=function(a,d,b){a.detachEvent?a.detachEvent("on"+d,b):a.removeEventListener(d,b,!1)};j.fixEolChars=function(a){a=a.replace(/\r\n/g,"\n");return a=a.replace(/\r/g,"\n")};j.extendRegExp=function(a,d,b){if(null===d||void 0===d)d="";if(null===b||void 0===b)b="";var a=a.toString(),c,a=a.replace(/\/([gim]*)$/,function(a,b){c=b;return""}),a=a.replace(/(^\/|\/$)/g,"");return new w(d+a+b,c)};q.getTop=function(a,d){var b=a.offsetTop;if(!d)for(;a=
a.offsetParent;)b+=a.offsetTop;return b};q.getHeight=function(a){return a.offsetHeight||a.scrollHeight};q.getWidth=function(a){return a.offsetWidth||a.scrollWidth};q.getPageSize=function(){var a,d,b,c;self.innerHeight&&self.scrollMaxY?(a=i.body.scrollWidth,d=self.innerHeight+self.scrollMaxY):i.body.scrollHeight>i.body.offsetHeight?(a=i.body.scrollWidth,d=i.body.scrollHeight):(a=i.body.offsetWidth,d=i.body.offsetHeight);self.innerHeight?(b=self.innerWidth,c=self.innerHeight):i.documentElement&&i.documentElement.clientHeight?
(b=i.documentElement.clientWidth,c=i.documentElement.clientHeight):i.body&&(b=i.body.clientWidth,c=i.body.clientHeight);a=Math.max(a,b);d=Math.max(d,c);return[a,d,b,c]};z.createBackground=function(){var a=i.createElement("div"),d=a.style;a.className="wmd-prompt-background";d.position="absolute";d.top="0";d.zIndex="1000";m?d.filter="alpha(opacity=50)":d.opacity="0.5";var b=q.getPageSize();d.height=b[1]+"px";m?(d.left=i.documentElement.scrollLeft,d.width=i.documentElement.clientWidth):(d.left="0",d.width=
"100%");i.body.appendChild(a);return a};z.prompt=function(a,d,b){var c,e;void 0===d&&(d="");var g=function(a){27===(a.charCode||a.keyCode)&&k(!0)},k=function(a){j.removeEvent(i.body,"keydown",g);var d=e.value;a?d=null:(d=d.replace(/^http:\/\/(https?|ftp):\/\//,"$1://"),/^(?:https?|ftp):\/\//.test(d)||(d="http://"+d));c.parentNode.removeChild(c);b(d);return!1},h=function(){c=i.createElement("div");c.className="wmd-prompt-dialog";c.style.padding="10px;";c.style.position="fixed";c.style.width="400px";
c.style.zIndex="1001";var b=i.createElement("div");b.innerHTML=a;b.style.padding="5px";c.appendChild(b);var b=i.createElement("form"),l=b.style;b.onsubmit=function(){return k(!1)};l.padding="0";l.margin="0";l.cssFloat="left";l.width="100%";l.textAlign="center";l.position="relative";c.appendChild(b);e=i.createElement("input");e.type="text";e.value=d;l=e.style;l.display="block";l.width="80%";l.marginLeft=l.marginRight="auto";b.appendChild(e);var r=i.createElement("input");r.type="button";r.onclick=
function(){return k(!1)};r.value="OK";l=r.style;l.margin="10px";l.display="inline";l.width="7em";var h=i.createElement("input");h.type="button";h.onclick=function(){return k(!0)};h.value="Cancel";l=h.style;l.margin="10px";l.display="inline";l.width="7em";b.appendChild(r);b.appendChild(h);j.addEvent(i.body,"keydown",g);c.style.top="50%";c.style.left="50%";c.style.display="block";p&&(c.style.position="absolute",c.style.top=i.documentElement.scrollTop+200+"px",c.style.left="50%");i.body.appendChild(c);
c.style.marginTop=-(q.getHeight(c)/2)+"px";c.style.marginLeft=-(q.getWidth(c)/2)+"px"};setTimeout(function(){h();var a=d.length;if(void 0!==e.selectionStart)e.selectionStart=0,e.selectionEnd=a;else if(e.createTextRange){var c=e.createTextRange();c.collapse(!1);c.moveStart("character",-a);c.moveEnd("character",a);c.select()}e.focus()},0)};var v=C.prototype;v.prefixes="(?:\\s{4,}|\\s*>|\\s*-\\s+|\\s*\\d+\\.|=|\\+|-|_|\\*|#|\\s*\\[[^\n]]+\\]:)";v.unwrap=function(a){var d=new w("([^\\n])\\n(?!(\\n|"+
this.prefixes+"))","g");a.selection=a.selection.replace(d,"$1 $2")};v.wrap=function(a,d){this.unwrap(a);var b=new w("(.{1,"+d+"})( +|$\\n?)","gm"),c=this;a.selection=a.selection.replace(b,function(a,b){return(new w("^"+c.prefixes,"")).test(a)?a:b+"\n"});a.selection=a.selection.replace(/\s+$/,"")};v.doBold=function(a,d){return this.doBorI(a,d,2,this.getString("boldexample"))};v.doItalic=function(a,d){return this.doBorI(a,d,1,this.getString("italicexample"))};v.doBorI=function(a,d,b,c){a.trimWhitespace();
a.selection=a.selection.replace(/\n{2,}/g,"\n");var e=/(\**$)/.exec(a.before)[0],d=/(^\**)/.exec(a.after)[0],e=Math.min(e.length,d.length);e>=b&&(2!=e||1!=b)?(a.before=a.before.replace(w("[*]{"+b+"}$",""),""),a.after=a.after.replace(w("^[*]{"+b+"}",""),"")):!a.selection&&d?(a.after=a.after.replace(/^([*_]*)/,""),a.before=a.before.replace(/(\s?)$/,""),a.before=a.before+d+w.$1):(!a.selection&&!d&&(a.selection=c),b=1>=b?"*":"**",a.before+=b,a.after=b+a.after)};v.stripLinkDefs=function(a,d){return a=
a.replace(/^[ ]{0,3}\[(\d+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|$)/gm,function(a,c,e,g,k){d[c]=a.replace(/\s*$/,"");return g?(d[c]=a.replace(/["(](.+?)[")]$/,""),g+k):""})};v.addLinkDef=function(a,d){var b=0,c={};a.before=this.stripLinkDefs(a.before,c);a.selection=this.stripLinkDefs(a.selection,c);a.after=this.stripLinkDefs(a.after,c);var e="",g=/(\[)((?:\[[^\]]*\]|[^\[\]])*)(\][ ]?(?:\n[ ]*)?\[)(\d+)(\])/g,k=function(a){b++;a=a.replace(/^[ ]{0,3}\[(\d+)\]:/,
"  ["+b+"]:");e+="\n"+a},h=function(a,e,d,i,f,j){d=d.replace(g,h);return c[f]?(k(c[f]),e+d+i+b+j):a};a.before=a.before.replace(g,h);d?k(d):a.selection=a.selection.replace(g,h);var i=b;a.after=a.after.replace(g,h);a.after&&(a.after=a.after.replace(/\n*$/,""));a.after||(a.selection=a.selection.replace(/\n*$/,""));a.after+="\n\n"+e;return i};v.doLinkOrImage=function(a,d,b){a.trimWhitespace();a.findTags(/\s*!?\[/,/\][ ]?(?:\n[ ]*)?(\[.*?\])?/);var c;if(1<a.endTag.length&&0<a.startTag.length)a.startTag=
a.startTag.replace(/!?\[/,""),a.endTag="",this.addLinkDef(a,null);else if(a.selection=a.startTag+a.selection+a.endTag,a.startTag=a.endTag="",/\n\n/.test(a.selection))this.addLinkDef(a,null);else{var e=this,g=function(g){c.parentNode.removeChild(c);null!==g&&(a.selection=(" "+a.selection).replace(/([^\\](?:\\\\)*)(?=[[\]])/g,"$1\\").substr(1),g=" [999]: "+A(g),g=e.addLinkDef(a,g),a.startTag=b?"![":"[",a.endTag="]["+g+"]",a.selection||(a.selection=b?e.getString("imagedescription"):e.getString("linkdescription")));
d()};c=z.createBackground();b?this.hooks.insertImageDialog(g)||z.prompt(this.getString("imagedialog"),"http://",g):z.prompt(this.getString("linkdialog"),"http://",g);return!0}};v.doAutoindent=function(a){var d=!1;a.before=a.before.replace(/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ ]{0,3}>[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ \t]+\n$/,"\n\n");!a.selection&&!/^[ \t]*(?:\n|$)/.test(a.after)&&(a.after=a.after.replace(/^[^\n]*/,function(b){a.selection=
b;return""}),d=!0);/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]+.*\n$/.test(a.before)&&this.doList&&this.doList(a);/(\n|^)[ ]{0,3}>[ \t]+.*\n$/.test(a.before)&&this.doBlockquote&&this.doBlockquote(a);/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&this.doCode&&this.doCode(a);d&&(a.after=a.selection+a.after,a.selection="")};v.doBlockquote=function(a){a.selection=a.selection.replace(/^(\n*)([^\r]+?)(\n*)$/,function(c,b,e,d){a.before+=b;a.after=d+a.after;return e});a.before=a.before.replace(/(>[ \t]*)$/,function(c,
b){a.selection=b+a.selection;return""});a.selection=a.selection.replace(/^(\s|>)+$/,"");a.selection=a.selection||this.getString("quoteexample");var d="",b="",c;if(a.before){for(var e=a.before.replace(/\n$/,"").split("\n"),g=!1,k=0;k<e.length;k++){var h=!1;c=e[k];g=g&&0<c.length;/^>/.test(c)?(h=!0,!g&&1<c.length&&(g=!0)):h=/^[ \t]*$/.test(c)?!0:g;h?d+=c+"\n":(b+=d+c,d="\n")}/(^|\n)>/.test(d)||(b+=d,d="")}a.startTag=d;a.before=b;a.after&&(a.after=a.after.replace(/^\n?/,"\n"));a.after=a.after.replace(/^(((\n|^)(\n[ \t]*)*>(.+\n)*.*)+(\n[ \t]*)*)/,
function(c){a.endTag=c;return""});d=function(c){var b=c?"> ":"";a.startTag&&(a.startTag=a.startTag.replace(/\n((>|\s)*)\n$/,function(a,c){return"\n"+c.replace(/^[ ]{0,3}>?[ \t]*$/gm,b)+"\n"}));a.endTag&&(a.endTag=a.endTag.replace(/^\n((>|\s)*)\n/,function(a,c){return"\n"+c.replace(/^[ ]{0,3}>?[ \t]*$/gm,b)+"\n"}))};/^(?![ ]{0,3}>)/m.test(a.selection)?(this.wrap(a,70),a.selection=a.selection.replace(/^/gm,"> "),d(!0),a.skipLines()):(a.selection=a.selection.replace(/^[ ]{0,3}> ?/gm,""),this.unwrap(a),
d(!1),!/^(\n|^)[ ]{0,3}>/.test(a.selection)&&a.startTag&&(a.startTag=a.startTag.replace(/\n{0,2}$/,"\n\n")),!/(\n|^)[ ]{0,3}>.*$/.test(a.selection)&&a.endTag&&(a.endTag=a.endTag.replace(/^\n{0,2}/,"\n\n")));a.selection=this.hooks.postBlockquoteCreation(a.selection);/\n/.test(a.selection)||(a.selection=a.selection.replace(/^(> *)/,function(c,b){a.startTag+=b;return""}))};v.doCode=function(a){var d=/\S[ ]*$/.test(a.before);if(!/^[ ]*\S/.test(a.after)&&!d||/\n/.test(a.selection)){a.before=a.before.replace(/[ ]{4}$/,
function(c){a.selection=c+a.selection;return""});var b=d=1;/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&(d=0);/^\n(\t|[ ]{4,})/.test(a.after)&&(b=0);a.skipLines(d,b);a.selection?/^[ ]{0,3}\S/m.test(a.selection)?/\n/.test(a.selection)?a.selection=a.selection.replace(/^/gm,"    "):a.before+="    ":a.selection=a.selection.replace(/^(?:[ ]{4}|[ ]{0,3}\t)/gm,""):(a.startTag="    ",a.selection=this.getString("codeexample"))}else a.trimWhitespace(),a.findTags(/`/,/`/),!a.startTag&&!a.endTag?(a.startTag=a.endTag=
"`",a.selection||(a.selection=this.getString("codeexample"))):a.endTag&&!a.startTag?(a.before+=a.endTag,a.endTag=""):a.startTag=a.endTag=""};v.doList=function(a,d,b){var d=/^\n*(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*/,c="-",e=1,g=function(){var a;b?(a=" "+e+". ",e++):a=" "+c+" ";return a},k=function(a){void 0===b&&(b=/^\s*\d/.test(a));return a=a.replace(/^[ ]{0,3}([*+-]|\d+[.])\s/gm,function(){return g()})};a.findTags(/(\n|^)*[ ]{0,3}([*+-]|\d+[.])\s+/,
null);a.before&&!/\n$/.test(a.before)&&!/^\n/.test(a.startTag)&&(a.before+=a.startTag,a.startTag="");if(a.startTag){var h=/\d+[.]/.test(a.startTag);a.startTag="";a.selection=a.selection.replace(/\n[ ]{4}/g,"\n");this.unwrap(a);a.skipLines();h&&(a.after=a.after.replace(d,k));if(b==h)return}var i=1;a.before=a.before.replace(/(\n|^)(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*$/,function(a){/^\s*([*+-])/.test(a)&&(c=w.$1);i=/[^\n]\n\n[^\n]/.test(a)?1:0;
return k(a)});a.selection||(a.selection=this.getString("litem"));var h=g(),l=1;a.after=a.after.replace(d,function(a){l=/[^\n]\n\n[^\n]/.test(a)?1:0;return k(a)});a.trimWhitespace(!0);a.skipLines(i,l,!0);a.startTag=h;d=h.replace(/./g," ");this.wrap(a,72-d.length);a.selection=a.selection.replace(/\n/g,"\n"+d)};v.doHeading=function(a){a.selection=a.selection.replace(/\s+/g," ");a.selection=a.selection.replace(/(^\s+|\s+$)/g,"");if(a.selection){var d=0;a.findTags(/#+[ ]*/,/[ ]*#+/);/#+/.test(a.startTag)&&
(d=w.lastMatch.length);a.startTag=a.endTag="";a.findTags(null,/\s?(-+|=+)/);/=+/.test(a.endTag)&&(d=1);/-+/.test(a.endTag)&&(d=2);a.startTag=a.endTag="";a.skipLines(1,1);d=0==d?2:d-1;if(0<d){var d=2<=d?"-":"=",b=a.selection.length;72<b&&(b=72);for(a.endTag="\n";b--;)a.endTag+=d}}else a.startTag="## ",a.selection=this.getString("headingexample"),a.endTag=" ##"};v.doHorizontalRule=function(a){a.startTag="----------\n";a.selection="";a.skipLines(2,1,!0)}})();
(function(){function m(){for(var a=0;a<w.length;a++)w[a].refreshPreview()}function x(a){var c=a.match(/^\s*>\s*!/mg);if(c&&c.length==a.split("\n").length){var b=!1,a=a.replace(/(.*) (\w)/,function(a,c,e){b=!0;return c+"\n> "+e});b||(a=a.replace(/^(\s*>\s*)!/m,"$1&#33;"))}return a}function p(a){var c=/^\s*?[^\s!]/m,b=/^\s*?!/gm;return a=a.replace(/\<blockquote\>[\n\s]*?\<p\>[\n\s]*?(![\s\S]*?)\<\/p\>[\n\s]*?\<\/blockquote\>/g,function(a,e){if(c.test(e))return a;a=a.replace(e,e.replace(b,""));return a=
a.replace("<blockquote>",'<blockquote class="spoiler">')})}function u(a){if(!window.tagRendererRaw)return a;var c,b;return a=a.replace(/\[(meta-)?tag:([a-z0-9#+.-]+)\]/gi,function(e,d,g,k){if(!i&&d)return e;if(!c){for(var h=a,f=[],j=/<(a|code)[^>]*>/ig,n;null!=(n=j.exec(h));){f.push(n.index);n=RegExp("</"+n[1]+">","ig");n.lastIndex=j.lastIndex;if(null==n.exec(h))break;f.push(n.lastIndex);j.lastIndex=n.lastIndex}c=f;b=c.length}h=!1;for(f=0;f<b&&!(c[f]>k);f++)h=!h;if(h)return e;e=null;i&&!d&&(e=z);
return tagRendererRaw(sanitizeAndSplitTags(g)[0],e)})}function f(a){var c,b;"undefined"==typeof v&&(v=StackExchange.options.styleCode);v&&(c=n(a),b=n(c+a),a=A(a,c,b));a=o(a);v&&(a=j(a,c,b));return a}function o(a){return a.replace(/<[^>]*>?/gi,t)}function t(c){return c.match(a)||c.match(d)||c.match(b)?c:""}function s(a){if(""==a)return"";var c=/<\/?\w+[^>]*(\s|$|>)/g,b=a.toLowerCase().match(c),e=(b||[]).length;if(0==e)return a;for(var d,g,h,k=[],i=[],f=!1,j=0;j<e;j++)if(d=b[j].replace(/<\/?(\w+).*/,
"$1"),!(k[j]||-1<"<p><img><br><li><hr>".search("<"+d+">"))){g=b[j];h=-1;if(!/^<\//.test(g))for(g=j+1;g<e;g++)if(!k[g]&&b[g]=="</"+d+">"){h=g;break}-1==h?f=i[j]=!0:k[h]=!0}if(!f)return a;j=0;return a=a.replace(c,function(a){a=i[j]?"":a;j++;return a})}function n(a){a=(a.match(/~/g)||[]).length;return Array(a+2).join("~")}function C(a){if(/^lang-/.test(a))return a;var b="c_"+a,d=c[b];if(d)return d;if(e[b])return null;e[b]=!0;b=g.length;0<b&&RegExp("^"+g[b-1]).test(a)?g[b-1]=a:g.push(a);k.trigger();return null}
function A(a,c,b){a=a.replace(I,function(a,b,e){return c+b+c+e});return a.replace(D,function(a,c){return b+c+b})}function j(a,c,b){var a=a.replace(RegExp(c+"([a-z0-9#+.-]+)"+c+"(\\s*?<pre)","gi"),function(a,c,b){a=C(c);return!a?b:b+" class='"+a+" prettyprint-override'"}),e;return a.replace(RegExp("("+b+"([a-z0-9#+.-]+)"+b+")|(<pre><code>)","gi"),function(a,c,b){if(c)return e=b,"";if(!e)return a;c=C(e);return!c?a:"<pre class='"+c+" prettyprint-override'><code>"})}function q(a){function c(){d.animate({height:g.height()-
h})}function b(a){if(g)a();else if(!j){j=!0;var e=n.offset();h=e.top-$("#wmd-button-row"+f).offset().top-$("#wmd-button-row"+f).outerHeight()-5;k=$("#wmd-help-button"+f);var l=k.offset().left+k.outerWidth(),e=e.left,o=n.outerWidth()+e,o=Math.max(l,o);i={right:l-o,width:o-e,top:$("#wmd-button-row"+f).outerHeight()+5};k.addClass("active-help");d=$("<div style='clear:both' />").insertBefore(n);g=$('<div id="mdhelp'+f+'" class="mdhelp"><ul id="mdhelp-tabs'+f+'" class="mdhelp-tabs"><li /></ul></div>').find("li").addSpinner().end().css(i).insertAfter(k);
c();$.get("/posts/markdown-help",{postfix:f}).done(function(b){g.remove();g=$(b).insertAfter(k).css(i);$("#mdhelp-tabs"+f).delegate("li:not(:last-child)","click",function(){var a=$(this).hasClass("selected");g.find(".mdhelp-tab").hide();$("#mdhelp-tabs"+f+" li").removeClass("selected");if(!a&&($("#"+$(this).attr("data-tab")).show(),$(this).addClass("selected"),a=$(this).attr("data-buttons")))for(var a=a.split(","),b=0;b<a.length;b++){var e=$("#wmd-"+a[b]+"-button"+f);e.is(":animated")||e.animate({top:-15},
400).animate({top:0},400).animate({top:-8},300).animate({top:0},300).animate({top:-4},200).animate({top:0},200).animate({top:-2},100).animate({top:0},100).animate({top:-1},50).animate({top:0},50)}c()});j=!1;a()})}}function e(){o=!0;b(function(){k.addClass("active-help");g.show();c()})}var d,g,h,k,i,j=!1,f=(a||{}).postfix||"",n=$("#wmd-input"+f),o=!1;this.toggle=function(){g&&g.is(":visible")?(g.hide(),d.animate({height:0}),k.removeClass("active-help")):e()};this.showOnce=function(){o||e()}}if(!StackExchange.MarkdownEditor){var z,
i,w=[],E=function(a){function c(a){return"facebook.stackoverflow.com"===a?"stackoverflow.com":a}function b(c){window.apiCallbacks[c]||(window.apiCallbacks[c]=function(b){if(b)if(b.error_message)/^No site found/.test(b.error_message)&&(n["s_"+c]=!0);else if(b.items){for(var b=b.items,e=b.length,d=0;d<e;d++){var g=b[d];h[c+"|"+g.question_id]=g.title}a&&a()}});return'apiCallbacks["'+c+'"]'}function e(a,b){if(c(a)===k)return!0;var d=o[a];d||(d=o[a]={count:0,ids:{}});if(d.ids[b])return!0;if(d.count>=v)return!1;
d.count++;return d.ids[b]=!0}var d=/<a href="((\S+)\/q(?:uestions)?\/(\d+)(?:|\/\S*?))">\1<\/a>/g,g=window.location.hostname.toLowerCase(),k=c(g),h={},f={},i={},j=StackExchange.helpers.DelayedReaction(function(){var a=!1,e;for(e in i)if(i.hasOwnProperty(e)){var d=b(e),g;30<i[e].length?g=i[e].splice(0,30).join(";"):(g=i[e].join(";"),delete i[e]);a=!0;$.ajax({url:"http://api.stackexchange.com/2.0/questions/"+g+"?pagesize=30&key=6AU78DZ)GcdjNjAszYmTLQ((&filter=!6G7RPxWUNTleV&site="+c(e),crossDomain:!0,
jsonpCallback:d,dataType:"jsonp"});break}a&&j.trigger()},1E3,{sliding:!0}),n={};window.apiCallbacks={};var o={},v=/^meta\./.test(k)?40:10;return function(a){o={};return a.replace(d,function(a,b,d,g){d=d.toLowerCase().replace(/^http:\/\//,"");if(/[^a-z0-9.]/.test(d)||!e(d,g))return a;var l=h[d+"|"+g];if(l)g=l;else{if(l=!f[d+"|"+g]){l=c(d);if(l===k)l=!1;else if(n["s_"+l])l=!0;else var o=/^meta\./.test(k),l=k==="meta."+l||!o&&"meta."+k===l||o&&"meta.stackoverflow.com"==l||"meta.stackoverflow.com"===
k?!1:!0;l=!l}l&&(f[d+"|"+g]=!0,(l=i[d])||(l=i[d]=[]),l.push(g),j.trigger());g=null}return!g?a:'<a href="'+b+'">'+g+"</a>"})}}(m),h=$.Callbacks();StackExchange.MarkdownEditor=function(a){var c=a.postfix||"";z=$("#hlinks a").filter(function(){return"main"==$(this).text()}).attr("href");i=!!z;var b=new Markdown.Converter,e=b.hooks;e.addNoop("preSafe");e.chain("postConversion",E);e.chain("postConversion",function(a){return e.preSafe(a)});e.chain("postConversion",f);e.chain("postConversion",s);e.chain("postConversion",
p);e.chain("postConversion",u);var d=new q({postfix:c}),g={helpButton:{handler:d.toggle}};a.noCode&&(g.strings={code:"Preformatted text <pre><code> Ctrl-K",codeexample:"enter preformatted text here"});b=new Markdown.Editor(b,c,g);b.hooks.chain("postBlockquoteCreation",x);StackExchange.options.disableImageUploads||b.hooks.set("insertImageDialog",StackExchange.imageUploader.uploadImageDialog);h.fire(b,a.postfix);var k=$("#wmd-preview"+c);b.hooks.chain("onPreviewRefresh",function(){k.trigger("wmdrefresh")});
w.push(b);b.run();if(a.immediatelyShowMarkdownHelp)d.showOnce(a);else if(a.autoShowMarkdownHelp)$("#wmd-input"+c).one("focus",function(){d.showOnce(a)});b.disableSubmission=function(){$("#submit-button"+c).attr("disabled","disabled");StackExchange.navPrevention.stop()};return b};StackExchange.MarkdownEditor.creationCallbacks=h;StackExchange.MarkdownEditor.refreshAllPreviews=m;var v;StackExchange.MarkdownEditor.sanitizeHtml=o;var a=/^(<\/?(b|blockquote|code|del|dd|dl|dt|em|h1|h2|h3|i|kbd|li|ol|p|pre|s|sup|sub|strong|strike|ul)>|<(br|hr)\s?\/?>)$/i,
d=/^(<a\shref="((https?|ftp):\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\stitle="[^"<>]+")?\s?>|<\/a>)$/i,b=/^(<img\ssrc="(https?:\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\swidth="\d{1,3}")?(\sheight="\d{1,3}")?(\salt="[^"<>]*")?(\stitle="[^"<>]*")?\s?\/?>)$/i;StackExchange.MarkdownEditor.balanceTags=s;var c={},e={},g=[],k=StackExchange.helpers.DelayedReaction(function(){0!=g.length&&($.ajax("/api/tags/"+encodeURIComponent(g.join(";"))+"/syntax-highlight",{cache:!0}).done(function(a){var b=!1,
e;for(e in a)a.hasOwnProperty(e)&&(c["c_"+e]=a[e],b=!0);b&&(StackExchange.MarkdownEditor.refreshAllPreviews(),styleCode())}),g=[])},2E3,{sliding:!0}),I=/<\!-- language: ([a-z0-9#+\-.]+) --\>(\s*?<pre>\s*?<code>)/gi,D=/<\!-- language-all: ([a-z0-9#+\-.]+) --\>/gi}})();
StackExchange.editor=function(){var m=function(m){var m=m||{},p=m.postfix||"",u=m.heartbeatType,f=m.bindNavPrevention,o=$("#post-form"+p),t=$("#wmd-input"+p),s;s=$("#title, #edit-comment, #m-address, .edit-comment");p=s.add(".tag-editor input");o.submit(function(){s.each(function(){StackExchange.helpers.hideHelpOverlay($(this))});StackExchange.helpers.disableSubmitButton(o);StackExchange.navPrevention.stop();return!0});$(".original-question").not(".processed").TextAreaResizer();t.not(".processed").TextAreaResizer();
t.typeWatch({highlight:!1,wait:5E3,captureLength:5,callback:styleCode});var n=new StackExchange.MarkdownEditor(m);if(u){var C=m.discardSelector?$(m.discardSelector):null;StackExchange.cardiologist.addHeart(u,t,n,C,m.postId)}if("ask"==u||"answer"==u){var A=t.add(p),j=function(){StackExchange.helpers.loadTicks(o);A.unbind("keydown",j);return!0};A.bind("keydown",j)}f&&StackExchange.navPrevention.init(t);o.find(".wmd-preview").click(function(f){2!=f.which&&$(this).siblings().find("textarea").focus()});
StackExchange.helpers.bindHelpOverlayEvents(s);0==$("#ask-page-has-errors").length&&$("#title").is("input")&&$("#title").focus();if(m.oncreated)m.oncreated(n);if(m.discardSelector&&("ask"==u||"answer"==u||"moderatormessage"==u)){var q=$(m.discardSelector);q.click(function(f){f.preventDefault();if(confirm("Are you sure you want to discard your draft?"))return $("#title").val("").blur(),$("#question-suggestions").empty(),$("#wmd-input-42").val(""),$("#wmd-preview-42").html(""),$("#answer-from-ask").is(":visible")&&
$("#answer-from-ask").is(":checked")&&$("#answer-from-ask").click(),f=$("#tagnames"),0<f.length&&f[0].func_clear&&(f[0].func_clear(),f.blur()),t.val("").blur(),n.refreshPreview(),$.post("/post/discard-draft",{fkey:StackExchange.options.user.fkey,postType:u},function(){$("#draft-saved").hide();$("#draft-discarded").show();var f=null,f=function(){$("#draft-discarded").hide();$("#title").unbind("keypress",f);t.unbind("keypress",f)};$("#title").bind("keypress",f);t.bind("keypress",f)}),q.hide(),!1})}};
return{init:m,initIfShown:function(x){var p=(x||{}).postfix||"";0!=$("#wmd-preview"+p).length&&("-42"!==p||0===$("#answer-from-ask").length)&&0===$("#show-editor-button"+p).length?(m(x),StackExchange.editor.finallyInit||(StackExchange.editor.finallyInit=function(){})):StackExchange.editor.finallyInit=function(){m(x)}}}}();
StackExchange.cardiologist=function(){function m(h){h="number"===typeof h?h:1E3*(C+A);z&&(h=Math.max(h,6E3-((new Date).getTime()-z)));i&&clearTimeout(i);i=setTimeout(x,h)}function x(){i=null;if(!t.length){var h;t=[];o&&!o.isDisabled&&30>o.beatCount&&t.push(o);for(var j=0;j<f.length;j++)h=f[j],h!=o&&!h.isDisabled&&30>h.beatCount&&t.push(h);C=Math.max(15,Math.min(45,60/(t.length||1)))}t.length?(h=t.shift(),h.checkActive()?h.beat():m()):m()}function p(){}function u(h){var f=[];$.get("/questions/"+h,
function(a){a=$(a);a.find("div.answer").each(function(){var a=this.id.substring(7);0==$("#answer-"+a).length&&f.push(this.id)});if(0<f.length){var d="#"+f.join(",#"),a=a.find(d),d=$("div.answer:last");0==d.length&&(d=$("#answers-header"));a.hide();d.after(a);a.fadeIn("slow");d=$("div.answer").length;$(".subheader h2").text(d+" Answer"+(1<d?"s":""));StackExchange.vote.init(h);StackExchange.comments.init({post:a})}StackExchange.notify.close(q);j=!1},"html")}var f=[],o,t=[],s,n,C=45,A=0,j=!1,q=-2,z,
i,w={ask:function(h){if(h.relatedQuestions){var f=$("#how-to-format"),a=h.relatedQuestions!=n;a&&f.hide();f.empty().append("<h4>Similar Questions</h4>"+h.relatedQuestions);a&&showFadingHelpText(f);n=h.relatedQuestions}h.suggestedTags&&StackExchange.tagSuggestions&&StackExchange.tagSuggestions.suggest(h.suggestedTags)},answer:function(h,f){if(h&&!j)if(h.disableEditor)StackExchange.notify.show("This question has been "+h.message+" - no more answers will be accepted.",q),j=!0;else{var a=parseInt(h.message);
0<a&&(StackExchange.notify.show(a+" new answer"+(1==a?" has":"s have")+' been posted - <a id="load-new-answers">load new answers.</a>',q),j=!0,$("#load-new-answers").click(function(){u(f.postId)}))}},edit:function(h){h&&h.message&&StackExchange.notify.getMessageText(q)!=$("<span />").html(h.message).text()&&(StackExchange.notify.close(q),StackExchange.notify.show(h.message,q))},moderatormessage:function(){}};p.prototype={activate:function(){o=this;this.isActive||(this.isActive=!0,this.beatCount=0,
f.push(this),1===f.length&&m())},checkActive:function(){if(!this.isActive||this.isDisabled)return!1;return!this.jTextarea.closest("body").length?(delete this.jTextarea,this.isDisabled=!0,!1):!0},beat:function(h){var f=this,a={type:"POST",url:"/posts/"+this.postId+"/editor-heartbeat/"+this.type,dataType:"json",data:{}};h||(a.success=function(a){f.success(a)},a.error=function(){f.error()},a.complete=function(){f.complete()});if(this.shouldSendDraft()){var d={text:this.jTextarea.val()};"ask"===this.type&&
(d.title=$("#title").val(),d.tagnames=$("#tagnames").val(),d.answertext=$("#wmd-input-42").val());if(!s||s.heart!==this||s.title!==d.title||s.tagnames!==d.tagnames||s.text!==d.text||s.answertext!==d.answertext)a.data=d,s={heart:this,title:d.title,tagnames:d.tagnames,text:d.text,answertext:d.answertext}}if(h&&!("text"in a.data))return $.Deferred().resolve().promise();this.revisionGuid&&(a.data.clientRevisionGuid=this.revisionGuid);"answer"===this.type&&(h=$("#answers-header .answers-subheader h2").text().replace(/ answers?/i,
"")||"0",a.data.clientCount=h);z=(new Date).getTime();return $.ajax(a).promise()},shouldSendDraft:function(){return"edit"!==this.type&&o===this},success:function(h){w[this.type](h,this);h.disableEditor&&(this.editor.disableSubmission(),this.isDisabled=!0);h.draftSaved&&E(this.jTextarea,this.discardDraftLink);this.beatCount++;A=0},error:function(){$("#draft-saved").hide();o===this&&t.unshift(this);A=(new Date).getTime()%100/10},complete:function(){m()}};var E=function(h,f){var a=$("#draft-saved"),
d=function(){a.text("draft saved").fadeIn("fast")};a.is(":visible")?a.fadeOut("fast",d):d();f&&f.removeClass("dno").show();var b=function(a){if(115!=a.which||!a.ctrlKey||a.shiftKey||a.altKey)h.unbind("keypress",b),$("#draft-saved").fadeOut("fast")};h.bind("keypress",b);$("#draft-discarded").hide()};return{addHeart:function(h,f,a,d,b){var c=new p,e;c.type=h;c.jTextarea=f;c.discardDraftLink=d;switch(h){case "ask":e=0;break;case "answer":e=$("#post-id").val()||location.href.match(/\/questions\/(\d+)/i)[1];
break;case "edit":e=b||$("#post-id").val()||f.closest(".question, .answer").find(".vote input").val();h=f.closest(".inline-post");d=null;0<h.length&&(d=h[0].action.split("/").pop());d||(d=$("#client-revision-guid").val());c.revisionGuid=d;break;case "moderatormessage":e=+$("#moderator-message-to-user").attr("data-userid")}c.postId=e;c.editor=a;f.keypress(function(){c.activate()})},ensureDraftSaved:function(f,i){!o||!o.checkActive()?f():o.beat(i).done(f)},beatASAP:function(){m(1)},notifiedOfNewAnswer:function(){j=
!0},isHeartBeating:function(){if(null==f)return!1;for(var h=0;h<f.length;h++)if(!0==f[h].checkActive())return!0;return!1}}}();
StackExchange.navPrevention=function(){var m,x,p=function(){var f=!1;m.each(function(m){f=f||$(this).val()!==x[m]});return f},u=function(f){window.onbeforeunload=f?function(){if(m&&p())return f}:null},f=function(){u("You have started writing or editing a post.")};return{init:function(o){m=o.one("keypress",f);x=[];o.each(function(){x.push($(this).val())})},start:function(){m&&f()},stop:function(){m&&(m.unbind("keypress",f),u(null),m=null)},confirm:function(f){return m&&p()?confirm(f):!0}}}();
(function(m){function x(n){f=m(n.data.el);f.blur();t=n.clientY+document.documentElement.scrollTop;o=f.height()-t;f.css("opacity",0.25);m(document).mousemove(p).mouseup(u);return!1}function p(n){var m=n.clientY+document.documentElement.scrollTop,p=o+m;t>=m&&(p-=5);t=m;p=Math.max(s,p);f.height(p+"px");p<s&&u(n);return!1}function u(){m(document).unbind("mousemove",p).unbind("mouseup",u);f.css("opacity",1);f.focus();o=f=null;t=0}var f,o,t=0,s=32;m.fn.TextAreaResizer=function(){return this.each(function(){f=
m(this).addClass("processed");o=null;m(this).parent().append(m('<div class="grippie"></div>').bind("mousedown",{el:this},x));var n=m("div.grippie",m(this).parent())[0];n.style.marginRight=n.offsetWidth-m(this)[0].offsetWidth+"px"})}})(jQuery);"use strict";
StackExchange.imageUploader=function(){return{uploadImageDialog:function(m,x){var p="upload-iframe-"+(new Date).getTime();"undefined"===typeof x&&(x="/upload/image");var u="",f=window.FileReader&&window.FormData,o=f&&"ondrop"in window,t=f&&"onpaste"in document.body&&window.Clipboard;o&&t?u="(or paste or drag-and-drop)":o&&(u="(or drag-and-drop)");var s=$('<div class="popup" id="image-upload" style="z-index:1010; width: 420px;" tabindex="-1"><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><iframe id="'+
p+'" style="display:none;" src="about:blank" name="'+p+'"/><form action="'+x+'" id="upload-form" method="post" enctype="multipart/form-data"><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add Image</h2><input type="radio" name="source" id="computer" checked="checked" value="computer" /> <label for="computer">From my computer</label> <input type="file" name="filename" id="filename-input" value="browse" size="18" style="float: right; width: 250px;" /><div id="url-wrapper" style="float: right; border: 0; padding: 0; margin: 0; display: none;"><input type="text" name="upload-url" id="url-input" style="width: 250px;" /><span class="edit-field-overlay">http://example.com/image.png</span></div><br /><input type="radio" name="source" id="web" value="web" /> <label for="web">From the web</label><br /><br /><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"></p><p>'+
u+'</p><p style="position: absolute; font-size: smaller; bottom: 10px; width: 313px;">user contributions licensed under<br/><a href="http://creativecommons.org/licenses/by-sa/3.0/">cc-wiki with attribution required</a>&nbsp;(<a href="http://stackexchange.com/legal/content-policy">content policy</a>)</p><input type="submit" id="add-picture" value="Add picture" style="float: right;" /></div></form></div><script type="text/javascript">    StackExchange.helpers.bindMovablePopups();    StackExchange.helpers.bindHelpOverlayEvents($("#url-input"));<\/script>'),
n,C,A,j=function(a){27===(a.charCode||a.keyCode)&&q(null)},q=function(a){s&&s.fadeOutAndRemove();$("body").unbind("keydown",j);$("body").unbind("paste");void 0!==a&&m(a);C&&C.fadeOutAndRemove();return!1},z=function(a){q();C=$('<div class="popup" id="image-upload" style="z-index:1010;"><iframe id="'+p+'" style="display:none;" src="about:blank" name="'+p+'"/><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+
'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add a picture</h2><img src="'+a+'" style="max-width: 250px;padding: 5px;" /><br /><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"><span style="float: right;"><input type="button" id="confirm-upload" value="Confirm" />&nbsp;&nbsp;&nbsp;<a id="cancel-upload">cancel</a></span></div></form></div>    <script type="text/javascript">    StackExchange.helpers.bindMovablePopups();<\/script>');d(C)},i=function(a){a=
a||window.event;a.preventDefault&&a.preventDefault();n.style.backgroundColor="white";A=a.dataTransfer.files[0];a=new window.FileReader;a.onloadend=w;a.readAsDataURL(A);return!1},w=function(a){z(a.target.result)},E=function(a){a=a.originalEvent||window.event;if(a.clipboardData&&(a=a.clipboardData.items))for(var c=0;c<a.length;c++)if(-1!==a[c].type.indexOf("image")){A=a[c].getAsFile();var e=(window.URL||window.webkitURL).createObjectURL(A);z(e)}},h=function(){return!1},v=function(){return!1},a=function(){C.find("#upload-message").text("Uploading ").addSpinner();
if(window.FormData){var a=new window.FormData;a.append("uploadedImage",A);a.append("fkey",StackExchange.options.user.fkey);$.ajax({url:x,data:a,cache:!1,contentType:!1,processData:!1,type:"POST",success:function(a){$("#"+p).contents().find("html").html(a)}})}},d=function(){C.appendTo("#header").center().fadeIn("fast");$("body").keydown(j);C.find(".popup-close").click(function(){q(null)});$("#cancel-upload").click(function(){q(null)});$("#confirm-upload").click(a);window.closeDialog=q;window.displayUploadError=
function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a)}};s.appendTo("#header").center().fadeIn("fast").promise().done(function(){n=document.getElementById("image-upload");o&&(n.ondrop=i,n.ondragover=v,n.ondragleave=h);t&&$("body").bind("paste",E);s.find(".popup-close").click(function(){q(null)});s.find(":radio").change(function(){var a=s.find("#filename-input"),c=s.find("#url-wrapper");a.toggle();c.toggle();$("#upload-message").css({color:"inherit",fontWeight:"inherit"}).hide().text("");
c.is(":visible")&&s.find("#url-input").focus()});s.find("form").submit(function(){s.find("#upload-message").text("Uploading ").addSpinner();var a=s.find(":radio:checked").val(),c=s.find("#filename-input"),e=s.find("#url-wrapper"),d;if("web"==a){var f=c.next();c.detach();d=function(){c.insertBefore(f)}}else{var h=e.next();e.detach();d=function(){e.insertBefore(h)}}this.target=p;window.closeDialog=q;window.displayUploadError=function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a);
d();d=null};return!0});s.find("#filename-input").focus()});$("body").keydown(j);return!0}}}();
StackExchange.postValidation=function(){function m(a,e,b){var d=a.find('input[type="submit"]:visible'),h=d.length&&d.is(":enabled");h&&d.attr("disabled",!0);p(a);u(a,e,b);o(a);t(a);s(a);var i=function(){1!=e||a.find(E).length?(f(a),h&&d.attr("disabled",!1)):setTimeout(i,250)};i()}function x(){for(var a=0;a<d.length;a++)clearTimeout(d[a]);d=[]}function p(a){var e=a.find(i);e.length&&e.blur(function(){d.push(setTimeout(function(){var b=e.val(),d=$.trim(b);if(0==d.length)q(a,e);else{var f=e.data("min-length");
f&&d.length<f?j(e,["Title must be at least "+f+" characters."],n()):(f=e.data("max-length"))&&d.length>f?j(e,["Title cannot be longer than "+f+" characters."],n()):$.ajax({type:"POST",url:"/posts/validate-title",data:{title:b},success:function(b){b.success?q(a,e):j(e,b.errors.Title,n())},error:function(){q(a,e)}})}},b))})}function u(a,e,g){var f=a.find(w);f.length&&f.blur(function(){d.push(setTimeout(function(){var b=f.val(),d=$.trim(b);0==d.length?q(a,f):5==e?(b=f.data("min-length"))&&d.length<b?
j(f,["Wiki Body must be at least "+b+" characters. You entered "+d.length+"."],n()):q(a,f):(1==e||2==e)&&$.ajax({type:"POST",url:"/posts/validate-body",data:{body:b,oldBody:f.prop("defaultValue"),isQuestion:1==e,isSuggestedEdit:g},success:function(e){e.success?q(a,f):j(f,e.errors.Body,n())},error:function(){q(a,f)}})},b))})}function f(a){var e=a.find(E);if(e.length){var g=e.parent().find("input#tagnames");g.blur(function(){d.push(setTimeout(function(){var b=g.val();0==$.trim(b).length?q(a,e):$.ajax({type:"POST",
url:"/posts/validate-tags",data:{tags:b,oldTags:g.prop("defaultValue")},success:function(b){b.success?q(a,e):j(e,b.errors.Tags,n())},error:function(){q(a,e)}})},b))})}}function o(a){var e=a.find(h);e.length&&e.blur(function(){d.push(setTimeout(function(){var b=e.val(),b=$.trim(b);if(0==b.length)q(a,e);else{var d=e.data("min-length");d&&b.length<d?j(e,["Your edit summary must be at least "+d+" characters."],n()):(d=e.data("max-length"))&&b.length>d?j(e,["Your edit summary cannot be longer than "+d+
" characters."],n()):q(a,e)}},b))})}function t(a){var e=a.find(v);e.length&&e.blur(function(){d.push(setTimeout(function(){var b=e.val(),b=$.trim(b);if(0==b.length)q(a,e);else{var d=e.data("min-length");d&&b.length<d?j(e,["Wiki Excerpt must be at least "+d+" characters; you entered "+b.length+"."],n()):(d=e.data("max-length"))&&b.length>d?j(e,["Wiki Excerpt cannot be longer than "+d+" characters; you entered "+b.length+"."],n()):q(a,e)}},b))})}function s(c){var e=c.find(a);e.length&&e.blur(function(){d.push(setTimeout(function(){var a=
e.val();0==$.trim(a).length?q(c,e):/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,20}$/i.test(a)?q(c,e):j(e,["This email does not appear to be valid."],C())},b))})}function n(){var a=$("#sidebar, .sidebar").first().width()||270;return{position:{my:"left top",at:"right center"},css:{"max-width":a,"min-width":a},closeOthers:!1}}function C(){return{position:{my:"left top",at:"right center"},css:{"min-width":$("#sidebar, .sidebar").first().width()||270},closeOthers:!1}}function A(c,b,d,f){if(c){var m=function(){var d=
0;j(b.find(i),c.Title,n())?d++:q(b,b.find(i));j(b.find(w),c.Body,n())?d++:q(b,b.find(w));j(b.find(E),c.Tags,n())?d++:q(b,b.find(E));j(b.find(h),c.EditComment,n())?d++:q(b,b.find(h));j(b.find(v),c.Excerpt,n())?d++:q(b,b.find(v));j(b.find(a),c.Email,C())?d++:q(b,b.find(a));var g=b.find(".general-error"),m=c.General&&0<c.General.length;m||0<d?(g.length||(b.find('input[type="submit"]:visible').before('<div class="general-error-container"><div class="general-error"></div><br class="cbt" /></div>'),g=b.find(".general-error")),
m?j(g,c.General,{position:"inline",css:{"float":"left","margin-bottom":"10px"},closeOthers:!1,dismissable:!1}):(q(b,g),g.text("Your "+f+" couldn't be submitted. Please see the "+(1==d?"error":"errors")+" above."))):b.find(".general-error-container").remove();var o;z()&&($("#sidebar").animate({opacity:0.4},500),o=setInterval(function(){z()||($("#sidebar").animate({opacity:1},500),clearInterval(o))},500));var p;b.find(".validation-error").each(function(){var a=$(this).offset().top;if(!p||a<p)p=a});
d=function(){for(var a=0;3>a;a++)b.find(".message").animate({left:"+=5px"},100).animate({left:"-=5px"},100)};p?(g=$(".review-bar").length,p=Math.max(0,p-(g?125:30)),$("html, body").animate({scrollTop:p},d)):d()},o=function(){1!=d||b.find(E).length?m():setTimeout(o,250)};o()}}function j(a,b,d){if(!b||0==b.length||!a.length||!$("html").has(a).length)return!1;if((b=1==b.length?b[0]:"<ul><li>"+b.join("</li><li>")+"</li></ul>")&&0<b.length){var f=a.data("error-popup");if(f&&f.is(":visible")){if(a.data("error-message")==
b)return!0;f.fadeOutAndRemove()}d=StackExchange.helpers.showMessage(a,b,d);d.find("a").attr("target","_blank");a.addClass("validation-error");a.data("error-popup",d);a.data("error-message",b);d.click(x);return!0}return!1}function q(a,b){if(!b||0==b.length)return!1;var d=b.data("error-popup");d&&d.is(":visible")&&d.fadeOutAndRemove();b.removeClass("validation-error");b.removeData("error-popup");b.removeData("error-message");a.find(".validation-error").length||a.find(".general-error-container").remove();
return!0}function z(){var a=!1,b=$("#sidebar, .sidebar").first();if(!b.length)return!1;var d=b.offset().left;$(".message").each(function(){var b=$(this);if(b.offset().left+b.outerWidth()>d)return a=!0,!1});return a}var i="input#title",w="textarea.wmd-input:first",E=".tag-editor",h="input[id^=edit-comment]",v="textarea#excerpt",a="input#m-address",d=[],b=250;return{initOnBlur:m,initOnBlurAndSubmit:function(a,b,d,f,i){m(a,b,f);var o,l=function(f){if(f.success)if(i)i(f);else{var h=window.location.href.split("#")[0],
j=f.redirectTo.split("#")[0];0==j.indexOf("/")&&(j=window.location.protocol+"//"+window.location.hostname+j);o=!0;window.location=f.redirectTo;h.toLowerCase()==j.toLowerCase()&&window.location.reload(!0)}else f.captchaHtml?StackExchange.captcha.init(f.captchaHtml,l):f.errors?A(f.errors,a,b,d):a.find('input[type="submit"]:visible').parent().showErrorMessage(f.message)};a.submit(function(){if(a.find("#answer-from-ask").is(":checked"))return!0;var b=a.find(h);if("[Edit removed during grace period]"==
$.trim(b.val()))return j(b,["Comment reserved for system use.  Please use an appropriate comment."],n()),!1;x();StackExchange.navPrevention&&StackExchange.navPrevention.stop();a.find('input[type="submit"]:visible').parent().addSpinner();StackExchange.helpers.disableSubmitButton(a);setTimeout(function(){$.ajax({type:"POST",dataType:"json",data:a.serialize(),url:a.attr("action"),success:l,error:function(){a.find('input[type="submit"]:visible').parent().showErrorMessage("An error occurred submitting the "+
d+".")},complete:function(){StackExchange.helpers.removeSpinner();o||StackExchange.helpers.enableSubmitButton(a)}})},0);return!1})},showErrorsAfterSubmission:A,getSidebarPopupOptions:n}}();
